# Generated by Django 3.1.4 on 2021-01-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EMPLOYER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICLE',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('article_title', models.CharField(max_length=250)),
                ('article_desc', models.TextField(blank=True)),
                ('article_media', models.ImageField(blank=True, upload_to='ARTICLE/MEDIA/')),
                ('employer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPLOYER.employer')),
            ],
        ),
    ]
