# Generated by Django 3.1.2 on 2021-03-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOBSEEKER', '0001_initial'),
        ('EMPLOYER', '0001_initial'),
        ('ARTICLE', '0002_article_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOVEDPOST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPLOYER.employer')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBSEEKER.jobseeker')),
            ],
        ),
    ]
