# Generated by Django 3.1.2 on 2021-03-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE', '0003_lovedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovedpost',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARTICLE.article'),
        ),
    ]
