# Generated by Django 3.1.2 on 2021-03-18 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JOBSEEKER', '0001_initial'),
        ('ARTICLE', '0004_auto_20210318_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARTICLE.article')),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ARTICLE.comment')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBSEEKER.jobseeker')),
            ],
        ),
    ]
