# Generated by Django 3.1.2 on 2021-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenttext',
            field=models.TextField(default='Nice insight'),
        ),
    ]
