# Generated by Django 3.1.2 on 2021-03-21 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ARTICLE', '0007_auto_20210318_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOPIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('problem_link', models.URLField(blank=True, null=True)),
                ('p_in', models.TextField(blank=True, null=True)),
                ('p_out', models.TextField(blank=True, null=True)),
                ('p_exin', models.TextField(blank=True, null=True)),
                ('p_exout', models.TextField(blank=True, null=True)),
                ('p_code', models.TextField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARTICLE.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
