# Generated by Django 3.1.2 on 2021-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE', '0008_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraint',
            field=models.TextField(blank=True, default='default constraint', null=True),
        ),
    ]
