# Generated by Django 3.1.2 on 2021-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE', '0009_question_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pyurl',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True),
        ),
    ]
