# Generated by Django 3.1.2 on 2021-03-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
    ]
