# Generated by Django 3.1.4 on 2021-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOB_APPLICATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
            ],
        ),
    ]
