# Generated by Django 3.1.4 on 2021-01-03 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0002_job_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='jobseeker_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
