# Generated by Django 3.1.4 on 2021-01-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOBSEEKER', '0001_initial'),
        ('JOB', '0003_job_applications_jobseeker_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBSEEKER.jobseeker')),
                ('applicant_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.job')),
            ],
        ),
    ]
