# Generated by Django 3.1.2 on 2021-01-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOBSEEKER', '0001_initial'),
        ('JOB', '0004_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHORTLISTED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBSEEKER.jobseeker')),
                ('applicant_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.job')),
            ],
        ),
    ]
