# Generated by Django 3.1.2 on 2021-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0005_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlisted',
            name='hasSeen',
            field=models.BooleanField(default=False),
        ),
    ]
